version: '3.1'
services:
  web_odoo:
    image: odoo:16.0
    depends_on:
      - db_postgresql
    ports:
      - "8068:8069"
    volumes:
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
    environment:
      - HOST=db_postgresql
      - USER=odoo
      - PASSWORD=odoo
  db_postgresql:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo